# Permalinks
permalink:        /post/:title.html

# Setup
url:              https://baoduoliuhua.github.io
img_url:          https://baoduoliuhua.github.io/images

# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            '梓喵'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >




# Fallback image and color if not overwritten for tag or post
image:            /public/images/tuoer.jpg
color:            '#dc322f'

author:
  name:           '梓喵'
  email:          2717489190@qq.com
  github:         baoduoliuhua
  photo:          /public/images/wuming.jpg


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    想要变强！


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed

theme: jekyll-theme-cayman
